export default {
    ADD: 'ADD_NOTIFICATION',
    REMOVE: 'REMOVE_NOTIFICATION',
    RESET: 'RESET_NOTIFICATION',
    UPDATE: 'UPDATE_NOTIFICATION',
    GET: 'GET_NOTIFICATION',
    GETACTIVENOTIFICATION: 'GET_ACTIVE_NOTIFICATION',
    SETACCTIVENOTIFICATION: 'SET_ACTIVE_NOTIFICATION'
  };
  