export const NearlyCharacter = ' ≈ '
export default {
  USD: {
    code: 'USD',
    country: 'US',
    decimal_digits: 2,
    name: 'US Dollar',
    name_plural: 'US dollars',
    rounding: 0,
    symbol: '$',
    symbol_native: '$',
    displayOrder: 0,
  },
  GBP: {
    code: 'GBP',
    country: 'VG',
    decimal_digits: 2,
    name: 'Pound',
    name_plural: 'British pounds sterling',
    rounding: 0,
    symbol: '£',
    symbol_native: '£',
    displayOrder: 0,
  },
  EUR: {
    code: 'EUR',
    country: 'IE',
    decimal_digits: 2,
    name: 'Euro',
    name_plural: 'euros',
    rounding: 0,
    symbol: '€',
    symbol_native: '€',
    displayOrder: 2,
  },
  VND: {
    code: 'VND',
    country: 'VN',
    decimal_digits: 0,
    name: 'Việt Nam Đồng',
    name_plural: 'Vietnamese dong',
    rounding: 0,
    symbol: '₫',
    symbol_native: '₫',
    displayOrder: 3,
  },
  AED: {
    code: 'AED',
    country: 'AE',
    decimal_digits: 2,
    name: 'United Arab Emirates Dirham',
    name_plural: 'UAE dirhams',
    rounding: 0,
    symbol: 'AED',
    symbol_native: 'د.إ.‏',
  },
  AFN: {
    code: 'AFN',
    country: 'AF',
    decimal_digits: 0,
    name: 'Afghan Afghani',
    name_plural: 'Afghan Afghanis',
    rounding: 0,
    symbol: 'Af',
    symbol_native: '؋',
  },
  ALL: {
    code: 'ALL',
    country: 'AL',
    decimal_digits: 0,
    name: 'Albanian Lek',
    name_plural: 'Albanian lekë',
    rounding: 0,
    symbol: 'ALL',
    symbol_native: 'Lek',
  },
  AMD: {
    code: 'AMD',
    country: 'AM',
    decimal_digits: 0,
    name: 'Armenian Dram',
    name_plural: 'Armenian drams',
    rounding: 0,
    symbol: 'AMD',
    symbol_native: 'դր.',
  },
  ARS: {
    code: 'ARS',
    country: 'AR',
    decimal_digits: 2,
    name: 'Argentine Peso',
    name_plural: 'Argentine pesos',
    rounding: 0,
    symbol: 'AR$',
    symbol_native: '$',
  },
  AUD: {
    code: 'AUD',
    country: 'AU',
    decimal_digits: 2,
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
    rounding: 0,
    symbol: 'AU$',
    symbol_native: '$',
  },
  AZN: {
    code: 'AZN',
    country: 'AZ',
    decimal_digits: 2,
    name: 'Azerbaijani Manat',
    name_plural: 'Azerbaijani manats',
    rounding: 0,
    symbol: 'man.',
    symbol_native: 'ман.',
  },
  BAM: {
    code: 'BAM',
    country: 'BA',
    decimal_digits: 2,
    name: 'Bosnia-Herzegovina Convertible Mark',
    name_plural: 'Bosnia-Herzegovina convertible marks',
    rounding: 0,
    symbol: 'KM',
    symbol_native: 'KM',
  },
  BDT: {
    code: 'BDT',
    country: 'BD',
    decimal_digits: 2,
    name: 'Bangladeshi Taka',
    name_plural: 'Bangladeshi takas',
    rounding: 0,
    symbol: 'Tk',
    symbol_native: '৳',
  },
  BGN: {
    code: 'BGN',
    country: 'BG',
    decimal_digits: 2,
    name: 'Bulgarian Lev',
    name_plural: 'Bulgarian leva',
    rounding: 0,
    symbol: 'BGN',
    symbol_native: 'лв.',
  },
  BHD: {
    code: 'BHD',
    country: 'BH',
    decimal_digits: 3,
    name: 'Bahraini Dinar',
    name_plural: 'Bahraini dinars',
    rounding: 0,
    symbol: 'BD',
    symbol_native: 'د.ب.‏',
  },
  BIF: {
    code: 'BIF',
    country: 'BI',
    decimal_digits: 0,
    name: 'Burundian Franc',
    name_plural: 'Burundian francs',
    rounding: 0,
    symbol: 'FBu',
    symbol_native: 'FBu',
  },
  BND: {
    code: 'BND',
    country: 'BN',
    decimal_digits: 2,
    name: 'Brunei Dollar',
    name_plural: 'Brunei dollars',
    rounding: 0,
    symbol: 'BN$',
    symbol_native: '$',
  },
  BOB: {
    code: 'BOB',
    country: 'BO',
    decimal_digits: 2,
    name: 'Bolivian Boliviano',
    name_plural: 'Bolivian bolivianos',
    rounding: 0,
    symbol: 'Bs',
    symbol_native: 'Bs',
  },
  BRL: {
    code: 'BRL',
    country: 'BR',
    decimal_digits: 2,
    name: 'Brazilian Real',
    name_plural: 'Brazilian reals',
    rounding: 0,
    symbol: 'R$',
    symbol_native: 'R$',
  },
  BWP: {
    code: 'BWP',
    country: 'BW',
    decimal_digits: 2,
    name: 'Botswanan Pula',
    name_plural: 'Botswanan pulas',
    rounding: 0,
    symbol: 'BWP',
    symbol_native: 'P',
  },
  BYR: {
    code: 'BYR',
    country: 'BY',
    decimal_digits: 0,
    name: 'Belarusian Ruble',
    name_plural: 'Belarusian rubles',
    rounding: 0,
    symbol: 'BYR',
    symbol_native: 'BYR',
  },
  BZD: {
    code: 'BZD',
    country: 'BZ',
    decimal_digits: 2,
    name: 'Belize Dollar',
    name_plural: 'Belize dollars',
    rounding: 0,
    symbol: 'BZ$',
    symbol_native: '$',
  },
  CAD: {
    code: 'CAD',
    country: 'CA',
    decimal_digits: 2,
    name: 'Canadian Dollar',
    name_plural: 'Canadian dollars',
    rounding: 0,
    symbol: 'CA$',
    symbol_native: '$',
  },
  CDF: {
    code: 'CDF',
    country: 'CD',
    decimal_digits: 2,
    name: 'Congolese Franc',
    name_plural: 'Congolese francs',
    rounding: 0,
    symbol: 'CDF',
    symbol_native: 'FrCD',
  },
  CHF: {
    code: 'CHF',
    country: 'LI',
    decimal_digits: 2,
    name: 'Swiss Franc',
    name_plural: 'Swiss francs',
    rounding: 0.05,
    symbol: 'CHF',
    symbol_native: 'CHF',
  },
  CLP: {
    code: 'CLP',
    country: 'CL',
    decimal_digits: 0,
    name: 'Chilean Peso',
    name_plural: 'Chilean pesos',
    rounding: 0,
    symbol: 'CL$',
    symbol_native: '$',
  },
  CNY: {
    code: 'CNY',
    country: 'CN',
    decimal_digits: 2,
    name: 'Chinese Yuan',
    name_plural: 'Chinese yuan',
    rounding: 0,
    symbol: 'CN¥',
    symbol_native: 'CN¥',
  },
  COP: {
    code: 'COP',
    country: 'CO',
    decimal_digits: 0,
    name: 'Colombian Peso',
    name_plural: 'Colombian pesos',
    rounding: 0,
    symbol: 'CO$',
    symbol_native: '$',
  },
  CRC: {
    code: 'CRC',
    country: 'CR',
    decimal_digits: 0,
    name: 'Costa Rican Colón',
    name_plural: 'Costa Rican colóns',
    rounding: 0,
    symbol: '₡',
    symbol_native: '₡',
  },
  CVE: {
    code: 'CVE',
    country: 'CV',
    decimal_digits: 2,
    name: 'Cape Verdean Escudo',
    name_plural: 'Cape Verdean escudos',
    rounding: 0,
    symbol: 'CV$',
    symbol_native: 'CV$',
  },
  CZK: {
    code: 'CZK',
    country: 'CZ',
    decimal_digits: 2,
    name: 'Czech Republic Koruna',
    name_plural: 'Czech Republic korunas',
    rounding: 0,
    symbol: 'Kč',
    symbol_native: 'Kč',
  },
  DJF: {
    code: 'DJF',
    country: 'DJ',
    decimal_digits: 0,
    name: 'Djiboutian Franc',
    name_plural: 'Djiboutian francs',
    rounding: 0,
    symbol: 'Fdj',
    symbol_native: 'Fdj',
  },
  DKK: {
    code: 'DKK',
    country: 'DK',
    decimal_digits: 2,
    name: 'Danish Krone',
    name_plural: 'Danish kroner',
    rounding: 0,
    symbol: 'Dkr',
    symbol_native: 'kr',
  },
  DOP: {
    code: 'DOP',
    country: 'DO',
    decimal_digits: 2,
    name: 'Dominican Peso',
    name_plural: 'Dominican pesos',
    rounding: 0,
    symbol: 'RD$',
    symbol_native: 'RD$',
  },
  DZD: {
    code: 'DZD',
    country: 'DZ',
    decimal_digits: 2,
    name: 'Algerian Dinar',
    name_plural: 'Algerian dinars',
    rounding: 0,
    symbol: 'DA',
    symbol_native: 'د.ج.‏',
  },
  EEK: {
    code: 'EEK',
    decimal_digits: 2,
    name: 'Estonian Kroon',
    name_plural: 'Estonian kroons',
    rounding: 0,
    symbol: 'Ekr',
    symbol_native: 'kr',
  },
  EGP: {
    code: 'EGP',
    country: 'EG',
    decimal_digits: 2,
    name: 'Egyptian Pound',
    name_plural: 'Egyptian pounds',
    rounding: 0,
    symbol: 'EGP',
    symbol_native: 'ج.م.‏',
  },
  ERN: {
    code: 'ERN',
    country: 'ER',
    decimal_digits: 2,
    name: 'Eritrean Nakfa',
    name_plural: 'Eritrean nakfas',
    rounding: 0,
    symbol: 'Nfk',
    symbol_native: 'Nfk',
  },
  ETB: {
    code: 'ETB',
    country: 'ET',
    decimal_digits: 2,
    name: 'Ethiopian Birr',
    name_plural: 'Ethiopian birrs',
    rounding: 0,
    symbol: 'Br',
    symbol_native: 'Br',
  },
  GEL: {
    code: 'GEL',
    country: 'GE',
    decimal_digits: 2,
    name: 'Georgian Lari',
    name_plural: 'Georgian laris',
    rounding: 0,
    symbol: 'GEL',
    symbol_native: 'GEL',
  },
  GHS: {
    code: 'GHS',
    country: 'GH',
    decimal_digits: 2,
    name: 'Ghanaian Cedi',
    name_plural: 'Ghanaian cedis',
    rounding: 0,
    symbol: 'GH₵',
    symbol_native: 'GH₵',
  },
  GNF: {
    code: 'GNF',
    country: 'GN',
    decimal_digits: 0,
    name: 'Guinean Franc',
    name_plural: 'Guinean francs',
    rounding: 0,
    symbol: 'FG',
    symbol_native: 'FG',
  },
  GTQ: {
    code: 'GTQ',
    country: 'GT',
    decimal_digits: 2,
    name: 'Guatemalan Quetzal',
    name_plural: 'Guatemalan quetzals',
    rounding: 0,
    symbol: 'GTQ',
    symbol_native: 'Q',
  },
  HKD: {
    code: 'HKD',
    country: 'HK',
    decimal_digits: 2,
    name: 'Hong Kong Dollar',
    name_plural: 'Hong Kong dollars',
    rounding: 0,
    symbol: 'HK$',
    symbol_native: '$',
  },
  HNL: {
    code: 'HNL',
    country: 'HN',
    decimal_digits: 2,
    name: 'Honduran Lempira',
    name_plural: 'Honduran lempiras',
    rounding: 0,
    symbol: 'HNL',
    symbol_native: 'L',
  },
  HRK: {
    code: 'HRK',
    country: 'HR',
    decimal_digits: 2,
    name: 'Croatian Kuna',
    name_plural: 'Croatian kunas',
    rounding: 0,
    symbol: 'kn',
    symbol_native: 'kn',
  },
  HUF: {
    code: 'HUF',
    country: 'HU',
    decimal_digits: 0,
    name: 'Hungarian Forint',
    name_plural: 'Hungarian forints',
    rounding: 0,
    symbol: 'Ft',
    symbol_native: 'Ft',
  },
  IDR: {
    code: 'IDR',
    country: 'ID',
    decimal_digits: 0,
    name: 'Indonesian Rupiah',
    name_plural: 'Indonesian rupiahs',
    rounding: 0,
    symbol: 'Rp',
    symbol_native: 'Rp',
  },
  ILS: {
    code: 'ILS',
    country: 'IL',
    decimal_digits: 2,
    name: 'Israeli New Sheqel',
    name_plural: 'Israeli new sheqels',
    rounding: 0,
    symbol: '₪',
    symbol_native: '₪',
  },
  INR: {
    code: 'INR',
    country: 'IN',
    decimal_digits: 2,
    name: 'Indian Rupee',
    name_plural: 'Indian rupees',
    rounding: 0,
    symbol: 'Rs',
    symbol_native: 'টকা',
  },
  IQD: {
    code: 'IQD',
    country: 'IQ',
    decimal_digits: 0,
    name: 'Iraqi Dinar',
    name_plural: 'Iraqi dinars',
    rounding: 0,
    symbol: 'IQD',
    symbol_native: 'د.ع.‏',
  },
  IRR: {
    code: 'IRR',
    country: 'IR',
    decimal_digits: 0,
    name: 'Iranian Rial',
    name_plural: 'Iranian rials',
    rounding: 0,
    symbol: 'IRR',
    symbol_native: '﷼',
  },
  ISK: {
    code: 'ISK',
    country: 'IS',
    decimal_digits: 0,
    name: 'Icelandic Króna',
    name_plural: 'Icelandic krónur',
    rounding: 0,
    symbol: 'Ikr',
    symbol_native: 'kr',
  },
  JMD: {
    code: 'JMD',
    country: 'JM',
    decimal_digits: 2,
    name: 'Jamaican Dollar',
    name_plural: 'Jamaican dollars',
    rounding: 0,
    symbol: 'J$',
    symbol_native: '$',
  },
  JOD: {
    code: 'JOD',
    country: 'JO',
    decimal_digits: 3,
    name: 'Jordanian Dinar',
    name_plural: 'Jordanian dinars',
    rounding: 0,
    symbol: 'JD',
    symbol_native: 'د.أ.‏',
  },
  JPY: {
    code: 'JPY',
    country: 'JP',
    decimal_digits: 0,
    name: 'Japanese Yen',
    name_plural: 'Japanese yen',
    rounding: 0,
    symbol: '¥',
    symbol_native: '￥',
  },
  KES: {
    code: 'KES',
    country: 'KE',
    decimal_digits: 2,
    name: 'Kenyan Shilling',
    name_plural: 'Kenyan shillings',
    rounding: 0,
    symbol: 'Ksh',
    symbol_native: 'Ksh',
  },
  KHR: {
    code: 'KHR',
    country: 'KH',
    decimal_digits: 2,
    name: 'Cambodian Riel',
    name_plural: 'Cambodian riels',
    rounding: 0,
    symbol: 'KHR',
    symbol_native: '៛',
  },
  KMF: {
    code: 'KMF',
    country: 'KM',
    decimal_digits: 0,
    name: 'Comorian Franc',
    name_plural: 'Comorian francs',
    rounding: 0,
    symbol: 'CF',
    symbol_native: 'FC',
  },
  KRW: {
    code: 'KRW',
    country: 'KR',
    decimal_digits: 0,
    name: 'South Korean Won',
    name_plural: 'South Korean won',
    rounding: 0,
    symbol: '₩',
    symbol_native: '₩',
  },
  KWD: {
    code: 'KWD',
    country: 'KW',
    decimal_digits: 3,
    name: 'Kuwaiti Dinar',
    name_plural: 'Kuwaiti dinars',
    rounding: 0,
    symbol: 'KD',
    symbol_native: 'د.ك.‏',
  },
  KZT: {
    code: 'KZT',
    country: 'KZ',
    decimal_digits: 2,
    name: 'Kazakhstani Tenge',
    name_plural: 'Kazakhstani tenges',
    rounding: 0,
    symbol: 'KZT',
    symbol_native: 'тңг.',
  },
  LBP: {
    code: 'LBP',
    country: 'LB',
    decimal_digits: 0,
    name: 'Lebanese Pound',
    name_plural: 'Lebanese pounds',
    rounding: 0,
    symbol: 'LB£',
    symbol_native: 'ل.ل.‏',
  },
  LKR: {
    code: 'LKR',
    country: 'LK',
    decimal_digits: 2,
    name: 'Sri Lankan Rupee',
    name_plural: 'Sri Lankan rupees',
    rounding: 0,
    symbol: 'SLRs',
    symbol_native: 'SL Re',
  },
  LTL: {
    code: 'LTL',
    country: 'LT',
    decimal_digits: 2,
    name: 'Lithuanian Litas',
    name_plural: 'Lithuanian litai',
    rounding: 0,
    symbol: 'Lt',
    symbol_native: 'Lt',
  },
  LVL: {
    code: 'LVL',
    decimal_digits: 2,
    name: 'Latvian Lats',
    name_plural: 'Latvian lati',
    rounding: 0,
    symbol: 'Ls',
    symbol_native: 'Ls',
  },
  LYD: {
    code: 'LYD',
    country: 'LY',
    decimal_digits: 3,
    name: 'Libyan Dinar',
    name_plural: 'Libyan dinars',
    rounding: 0,
    symbol: 'LD',
    symbol_native: 'د.ل.‏',
  },
  MAD: {
    code: 'MAD',
    country: 'MA',
    decimal_digits: 2,
    name: 'Moroccan Dirham',
    name_plural: 'Moroccan dirhams',
    rounding: 0,
    symbol: 'MAD',
    symbol_native: 'د.م.‏',
  },
  MDL: {
    code: 'MDL',
    country: 'MD',
    decimal_digits: 2,
    name: 'Moldovan Leu',
    name_plural: 'Moldovan lei',
    rounding: 0,
    symbol: 'MDL',
    symbol_native: 'MDL',
  },
  MGA: {
    code: 'MGA',
    country: 'MG',
    decimal_digits: 0,
    name: 'Malagasy Ariary',
    name_plural: 'Malagasy Ariaries',
    rounding: 0,
    symbol: 'MGA',
    symbol_native: 'MGA',
  },
  MKD: {
    code: 'MKD',
    country: 'MK',
    decimal_digits: 2,
    name: 'Macedonian Denar',
    name_plural: 'Macedonian denari',
    rounding: 0,
    symbol: 'MKD',
    symbol_native: 'MKD',
  },
  MMK: {
    code: 'MMK',
    country: 'MM',
    decimal_digits: 0,
    name: 'Myanma Kyat',
    name_plural: 'Myanma kyats',
    rounding: 0,
    symbol: 'MMK',
    symbol_native: 'K',
  },
  MOP: {
    code: 'MOP',
    country: 'MO',
    decimal_digits: 2,
    name: 'Macanese Pataca',
    name_plural: 'Macanese patacas',
    rounding: 0,
    symbol: 'MOP$',
    symbol_native: 'MOP$',
  },
  MUR: {
    code: 'MUR',
    country: 'MU',
    decimal_digits: 0,
    name: 'Mauritian Rupee',
    name_plural: 'Mauritian rupees',
    rounding: 0,
    symbol: 'MURs',
    symbol_native: 'MURs',
  },
  MXN: {
    code: 'MXN',
    country: 'MX',
    decimal_digits: 2,
    name: 'Mexican Peso',
    name_plural: 'Mexican pesos',
    rounding: 0,
    symbol: 'MX$',
    symbol_native: '$',
  },
  MYR: {
    code: 'MYR',
    country: 'MY',
    decimal_digits: 2,
    name: 'Malaysian Ringgit',
    name_plural: 'Malaysian ringgits',
    rounding: 0,
    symbol: 'RM',
    symbol_native: 'RM',
  },
  MZN: {
    code: 'MZN',
    country: 'MZ',
    decimal_digits: 2,
    name: 'Mozambican Metical',
    name_plural: 'Mozambican meticals',
    rounding: 0,
    symbol: 'MTn',
    symbol_native: 'MTn',
  },
  NAD: {
    code: 'NAD',
    country: 'NA',
    decimal_digits: 2,
    name: 'Namibian Dollar',
    name_plural: 'Namibian dollars',
    rounding: 0,
    symbol: 'N$',
    symbol_native: 'N$',
  },
  NGN: {
    code: 'NGN',
    country: 'NG',
    decimal_digits: 2,
    name: 'Nigerian Naira',
    name_plural: 'Nigerian nairas',
    rounding: 0,
    symbol: '₦',
    symbol_native: '₦',
  },
  NIO: {
    code: 'NIO',
    country: 'NI',
    decimal_digits: 2,
    name: 'Nicaraguan Córdoba',
    name_plural: 'Nicaraguan córdobas',
    rounding: 0,
    symbol: 'C$',
    symbol_native: 'C$',
  },
  NOK: {
    code: 'NOK',
    country: 'NO',
    decimal_digits: 2,
    name: 'Norwegian Krone',
    name_plural: 'Norwegian kroner',
    rounding: 0,
    symbol: 'Nkr',
    symbol_native: 'kr',
  },
  NPR: {
    code: 'NPR',
    country: 'NP',
    decimal_digits: 2,
    name: 'Nepalese Rupee',
    name_plural: 'Nepalese rupees',
    rounding: 0,
    symbol: 'NPRs',
    symbol_native: 'नेरू',
  },
  NZD: {
    code: 'NZD',
    country: 'CK',
    decimal_digits: 2,
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand dollars',
    rounding: 0,
    symbol: 'NZ$',
    symbol_native: '$',
  },
  OMR: {
    code: 'OMR',
    country: 'OM',
    decimal_digits: 3,
    name: 'Omani Rial',
    name_plural: 'Omani rials',
    rounding: 0,
    symbol: 'OMR',
    symbol_native: 'ر.ع.‏',
  },
  PAB: {
    code: 'PAB',
    country: 'PA',
    decimal_digits: 2,
    name: 'Panamanian Balboa',
    name_plural: 'Panamanian balboas',
    rounding: 0,
    symbol: 'B/.',
    symbol_native: 'B/.',
  },
  PEN: {
    code: 'PEN',
    country: 'PE',
    decimal_digits: 2,
    name: 'Peruvian Nuevo Sol',
    name_plural: 'Peruvian nuevos soles',
    rounding: 0,
    symbol: 'S/.',
    symbol_native: 'S/.',
  },
  PHP: {
    code: 'PHP',
    country: 'PH',
    decimal_digits: 2,
    name: 'Philippine Peso',
    name_plural: 'Philippine pesos',
    rounding: 0,
    symbol: '₱',
    symbol_native: '₱',
  },
  PKR: {
    code: 'PKR',
    country: 'PK',
    decimal_digits: 0,
    name: 'Pakistani Rupee',
    name_plural: 'Pakistani rupees',
    rounding: 0,
    symbol: 'PKRs',
    symbol_native: '₨',
  },
  PLN: {
    code: 'PLN',
    country: 'PL',
    decimal_digits: 2,
    name: 'Polish Zloty',
    name_plural: 'Polish zlotys',
    rounding: 0,
    symbol: 'zł',
    symbol_native: 'zł',
  },
  PYG: {
    code: 'PYG',
    country: 'PY',
    decimal_digits: 0,
    name: 'Paraguayan Guarani',
    name_plural: 'Paraguayan guaranis',
    rounding: 0,
    symbol: '₲',
    symbol_native: '₲',
  },
  QAR: {
    code: 'QAR',
    country: 'QA',
    decimal_digits: 2,
    name: 'Qatari Rial',
    name_plural: 'Qatari rials',
    rounding: 0,
    symbol: 'QR',
    symbol_native: 'ر.ق.‏',
  },
  RON: {
    code: 'RON',
    country: 'RO',
    decimal_digits: 2,
    name: 'Romanian Leu',
    name_plural: 'Romanian lei',
    rounding: 0,
    symbol: 'RON',
    symbol_native: 'RON',
  },
  RSD: {
    code: 'RSD',
    country: 'RS',
    decimal_digits: 0,
    name: 'Serbian Dinar',
    name_plural: 'Serbian dinars',
    rounding: 0,
    symbol: 'din.',
    symbol_native: 'дин.',
  },
  RUB: {
    code: 'RUB',
    country: 'RU',
    decimal_digits: 2,
    name: 'Russian Ruble',
    name_plural: 'Russian rubles',
    rounding: 0,
    symbol: 'RUB',
    symbol_native: 'руб.',
  },
  RWF: {
    code: 'RWF',
    country: 'RW',
    decimal_digits: 0,
    name: 'Rwandan Franc',
    name_plural: 'Rwandan francs',
    rounding: 0,
    symbol: 'RWF',
    symbol_native: 'FR',
  },
  SAR: {
    code: 'SAR',
    country: 'SA',
    decimal_digits: 2,
    name: 'Saudi Riyal',
    name_plural: 'Saudi riyals',
    rounding: 0,
    symbol: 'SR',
    symbol_native: 'ر.س.‏',
  },
  SDG: {
    code: 'SDG',
    country: 'SD',
    decimal_digits: 2,
    name: 'Sudanese Pound',
    name_plural: 'Sudanese pounds',
    rounding: 0,
    symbol: 'SDG',
    symbol_native: 'SDG',
  },
  SEK: {
    code: 'SEK',
    country: 'SE',
    decimal_digits: 2,
    name: 'Swedish Krona',
    name_plural: 'Swedish kronor',
    rounding: 0,
    symbol: 'Skr',
    symbol_native: 'kr',
  },
  SGD: {
    code: 'SGD',
    country: 'SG',
    decimal_digits: 2,
    name: 'Singapore Dollar',
    name_plural: 'Singapore dollars',
    rounding: 0,
    symbol: 'S$',
    symbol_native: '$',
  },
  SOS: {
    code: 'SOS',
    country: 'SO',
    decimal_digits: 0,
    name: 'Somali Shilling',
    name_plural: 'Somali shillings',
    rounding: 0,
    symbol: 'Ssh',
    symbol_native: 'Ssh',
  },
  SYP: {
    code: 'SYP',
    country: 'SY',
    decimal_digits: 0,
    name: 'Syrian Pound',
    name_plural: 'Syrian pounds',
    rounding: 0,
    symbol: 'SY£',
    symbol_native: 'ل.س.‏',
  },
  THB: {
    code: 'THB',
    country: 'TH',
    decimal_digits: 2,
    name: 'Thai Baht',
    name_plural: 'Thai baht',
    rounding: 0,
    symbol: '฿',
    symbol_native: '฿',
  },
  TND: {
    code: 'TND',
    country: 'TN',
    decimal_digits: 3,
    name: 'Tunisian Dinar',
    name_plural: 'Tunisian dinars',
    rounding: 0,
    symbol: 'DT',
    symbol_native: 'د.ت.‏',
  },
  TOP: {
    code: 'TOP',
    country: 'TO',
    decimal_digits: 2,
    name: 'Tongan Paʻanga',
    name_plural: 'Tongan paʻanga',
    rounding: 0,
    symbol: 'T$',
    symbol_native: 'T$',
  },
  TRY: {
    code: 'TRY',
    country: 'TR',
    decimal_digits: 2,
    name: 'Turkish Lira',
    name_plural: 'Turkish Lira',
    rounding: 0,
    symbol: 'TL',
    symbol_native: 'TL',
  },
  TTD: {
    code: 'TTD',
    country: 'TT',
    decimal_digits: 2,
    name: 'Trinidad and Tobago Dollar',
    name_plural: 'Trinidad and Tobago dollars',
    rounding: 0,
    symbol: 'TT$',
    symbol_native: '$',
  },
  TWD: {
    code: 'TWD',
    country: 'TW',
    decimal_digits: 2,
    name: 'New Taiwan Dollar',
    name_plural: 'New Taiwan dollars',
    rounding: 0,
    symbol: 'NT$',
    symbol_native: 'NT$',
  },
  TZS: {
    code: 'TZS',
    country: 'TZ',
    decimal_digits: 0,
    name: 'Tanzanian Shilling',
    name_plural: 'Tanzanian shillings',
    rounding: 0,
    symbol: 'TSh',
    symbol_native: 'TSh',
  },
  UAH: {
    code: 'UAH',
    country: 'UA',
    decimal_digits: 2,
    name: 'Ukrainian Hryvnia',
    name_plural: 'Ukrainian hryvnias',
    rounding: 0,
    symbol: '₴',
    symbol_native: '₴',
  },
  UGX: {
    code: 'UGX',
    country: 'UG',
    decimal_digits: 0,
    name: 'Ugandan Shilling',
    name_plural: 'Ugandan shillings',
    rounding: 0,
    symbol: 'USh',
    symbol_native: 'USh',
  },
  UYU: {
    code: 'UYU',
    country: 'UY',
    decimal_digits: 2,
    name: 'Uruguayan Peso',
    name_plural: 'Uruguayan pesos',
    rounding: 0,
    symbol: '$U',
    symbol_native: '$',
  },
  UZS: {
    code: 'UZS',
    country: 'UZ',
    decimal_digits: 0,
    name: 'Uzbekistan Som',
    name_plural: 'Uzbekistan som',
    rounding: 0,
    symbol: 'UZS',
    symbol_native: 'UZS',
  },
  VEF: {
    code: 'VEF',
    country: 'VE',
    decimal_digits: 2,
    name: 'Venezuelan Bolívar',
    name_plural: 'Venezuelan bolívars',
    rounding: 0,
    symbol: 'Bs.F.',
    symbol_native: 'Bs.F.',
  },
  XAF: {
    code: 'XAF',
    country: 'TD',
    decimal_digits: 0,
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
    rounding: 0,
    symbol: 'FCFA',
    symbol_native: 'FCFA',
  },
  XOF: {
    code: 'XOF',
    country: 'TG',
    decimal_digits: 0,
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
    rounding: 0,
    symbol: 'CFA',
    symbol_native: 'CFA',
  },
  YER: {
    code: 'YER',
    country: 'YE',
    decimal_digits: 0,
    name: 'Yemeni Rial',
    name_plural: 'Yemeni rials',
    rounding: 0,
    symbol: 'YR',
    symbol_native: 'ر.ي.‏',
  },
  ZAR: {
    code: 'ZAR',
    country: 'ZA',
    decimal_digits: 2,
    name: 'South African Rand',
    name_plural: 'South African rand',
    rounding: 0,
    symbol: 'R',
    symbol_native: 'R',
  },
}
