// import Currency from './Currency';

// const Flags = {};
// Object.keys(Currency).map(function(key){
//     Flags[key] = require('@/Assets/Images/Flags/"+  key.toLowerCase() + ".png')";
// })

export default {
  AED: require('@/Assets/Images/Flags/aed.png'),
  AFN: require('@/Assets/Images/Flags/afn.png'),
  ALL: require('@/Assets/Images/Flags/all.png'),
  AMD: require('@/Assets/Images/Flags/amd.png'),
  ARS: require('@/Assets/Images/Flags/ars.png'),
  AUD: require('@/Assets/Images/Flags/aud.png'),
  AZN: require('@/Assets/Images/Flags/azn.png'),
  BAM: require('@/Assets/Images/Flags/bam.png'),
  BDT: require('@/Assets/Images/Flags/bdt.png'),
  BGN: require('@/Assets/Images/Flags/bgn.png'),
  BHD: require('@/Assets/Images/Flags/bhd.png'),
  BIF: require('@/Assets/Images/Flags/bif.png'),
  BND: require('@/Assets/Images/Flags/bnd.png'),
  BOB: require('@/Assets/Images/Flags/bob.png'),
  BRL: require('@/Assets/Images/Flags/brl.png'),
  BWP: require('@/Assets/Images/Flags/bwp.png'),
  // "BYR": require('@/Assets/Images/Flags/byr.png'),
  BZD: require('@/Assets/Images/Flags/bzd.png'),
  CAD: require('@/Assets/Images/Flags/cad.png'),
  CDF: require('@/Assets/Images/Flags/cdf.png'),
  CHF: require('@/Assets/Images/Flags/chf.png'),
  CLP: require('@/Assets/Images/Flags/clp.png'),
  CNY: require('@/Assets/Images/Flags/cny.png'),
  COP: require('@/Assets/Images/Flags/cop.png'),
  CRC: require('@/Assets/Images/Flags/crc.png'),
  CVE: require('@/Assets/Images/Flags/cve.png'),
  CZK: require('@/Assets/Images/Flags/czk.png'),
  DJF: require('@/Assets/Images/Flags/djf.png'),
  DKK: require('@/Assets/Images/Flags/dkk.png'),
  DOP: require('@/Assets/Images/Flags/dop.png'),
  DZD: require('@/Assets/Images/Flags/dzd.png'),
  // "EEK": require('@/Assets/Images/Flags/eek.png'),
  EGP: require('@/Assets/Images/Flags/egp.png'),
  ERN: require('@/Assets/Images/Flags/ern.png'),
  ETB: require('@/Assets/Images/Flags/etb.png'),
  EUR: require('@/Assets/Images/Flags/eur.png'),
  GBP: require('@/Assets/Images/Flags/gbp.png'),
  GEL: require('@/Assets/Images/Flags/gel.png'),
  GHS: require('@/Assets/Images/Flags/ghs.png'),
  GNF: require('@/Assets/Images/Flags/gnf.png'),
  GTQ: require('@/Assets/Images/Flags/gtq.png'),
  HKD: require('@/Assets/Images/Flags/hkd.png'),
  HNL: require('@/Assets/Images/Flags/hnl.png'),
  HRK: require('@/Assets/Images/Flags/hrk.png'),
  HUF: require('@/Assets/Images/Flags/huf.png'),
  IDR: require('@/Assets/Images/Flags/idr.png'),
  ILS: require('@/Assets/Images/Flags/ils.png'),
  INR: require('@/Assets/Images/Flags/inr.png'),
  IQD: require('@/Assets/Images/Flags/iqd.png'),
  IRR: require('@/Assets/Images/Flags/irr.png'),
  ISK: require('@/Assets/Images/Flags/isk.png'),
  JMD: require('@/Assets/Images/Flags/jmd.png'),
  JOD: require('@/Assets/Images/Flags/jod.png'),
  JPY: require('@/Assets/Images/Flags/jpy.png'),
  KES: require('@/Assets/Images/Flags/kes.png'),
  KHR: require('@/Assets/Images/Flags/khr.png'),
  KMF: require('@/Assets/Images/Flags/kmf.png'),
  KRW: require('@/Assets/Images/Flags/krw.png'),
  KWD: require('@/Assets/Images/Flags/kwd.png'),
  KZT: require('@/Assets/Images/Flags/kzt.png'),
  LBP: require('@/Assets/Images/Flags/lbp.png'),
  LKR: require('@/Assets/Images/Flags/lkr.png'),
  LTL: require('@/Assets/Images/Flags/ltl.png'),
  // "LVL": require('@/Assets/Images/Flags/lvl.png'),
  LYD: require('@/Assets/Images/Flags/lyd.png'),
  MAD: require('@/Assets/Images/Flags/mad.png'),
  MDL: require('@/Assets/Images/Flags/mdl.png'),
  MGA: require('@/Assets/Images/Flags/mga.png'),
  MKD: require('@/Assets/Images/Flags/mkd.png'),
  MMK: require('@/Assets/Images/Flags/mmk.png'),
  MOP: require('@/Assets/Images/Flags/mop.png'),
  MUR: require('@/Assets/Images/Flags/mur.png'),
  MXN: require('@/Assets/Images/Flags/mxn.png'),
  MYR: require('@/Assets/Images/Flags/myr.png'),
  MZN: require('@/Assets/Images/Flags/mzn.png'),
  NAD: require('@/Assets/Images/Flags/nad.png'),
  NGN: require('@/Assets/Images/Flags/ngn.png'),
  NIO: require('@/Assets/Images/Flags/nio.png'),
  NOK: require('@/Assets/Images/Flags/nok.png'),
  NPR: require('@/Assets/Images/Flags/npr.png'),
  NZD: require('@/Assets/Images/Flags/nzd.png'),
  OMR: require('@/Assets/Images/Flags/omr.png'),
  // "PAB": require('@/Assets/Images/Flags/pab.png'),
  PEN: require('@/Assets/Images/Flags/pen.png'),
  PHP: require('@/Assets/Images/Flags/php.png'),
  PKR: require('@/Assets/Images/Flags/pkr.png'),
  PLN: require('@/Assets/Images/Flags/pln.png'),
  PYG: require('@/Assets/Images/Flags/pyg.png'),
  QAR: require('@/Assets/Images/Flags/qar.png'),
  RON: require('@/Assets/Images/Flags/ron.png'),
  RSD: require('@/Assets/Images/Flags/rsd.png'),
  RUB: require('@/Assets/Images/Flags/rub.png'),
  RWF: require('@/Assets/Images/Flags/rwf.png'),
  SAR: require('@/Assets/Images/Flags/sar.png'),
  // "SDG": require('@/Assets/Images/Flags/sdg.png'),
  SEK: require('@/Assets/Images/Flags/sek.png'),
  SGD: require('@/Assets/Images/Flags/sgd.png'),
  SOS: require('@/Assets/Images/Flags/sos.png'),
  SYP: require('@/Assets/Images/Flags/syp.png'),
  THB: require('@/Assets/Images/Flags/thb.png'),
  TND: require('@/Assets/Images/Flags/tnd.png'),
  TOP: require('@/Assets/Images/Flags/top.png'),
  TRY: require('@/Assets/Images/Flags/try.png'),
  TTD: require('@/Assets/Images/Flags/ttd.png'),
  TWD: require('@/Assets/Images/Flags/twd.png'),
  TZS: require('@/Assets/Images/Flags/tzs.png'),
  UAH: require('@/Assets/Images/Flags/uah.png'),
  UGX: require('@/Assets/Images/Flags/ugx.png'),
  USD: require('@/Assets/Images/Flags/usd.png'),
  UYU: require('@/Assets/Images/Flags/uyu.png'),
  UZS: require('@/Assets/Images/Flags/uzs.png'),
  VEF: require('@/Assets/Images/Flags/vef.png'),
  VND: require('@/Assets/Images/Flags/vnd.png'),
  XAF: require('@/Assets/Images/Flags/xaf.png'),
  XOF: require('@/Assets/Images/Flags/xof.png'),
  YER: require('@/Assets/Images/Flags/yer.png'),
  ZAR: require('@/Assets/Images/Flags/zar.png'),
}
